### ISSUE TITLE
require loading and executing order

### ISSUE THREAD

**Issue by floriangaechter** [brunschgi/terrificjs#11]
In some cases it would be nice to be able to load dependencies in a certain order, e.g., if plugins are depending on each other. http://labjs.com/ has a nice way of handling this.

**Comment by brunschgi** [comment]
In v2.0 the resource loading part is completely stripped away in favor to use any of the existing, more powerful resource loader out there (we recommend yepnope.js). Have a look at the development branch for a first glimpse.
