### ISSUE TITLE
Dynamic Connectors

### ISSUE THREAD

**Issue by tjunghans** [brunschgi/terrificjs#2]
Hi Remo

Would it be possible to provide the sandbox with the possibility to add connectors dynamically or manually instead of having to make **application** in the bootstrap public.

Something like this or similar should be possible:

**current**

``` javascript
application.registerConnection('1', this);
```

**new**

``` javascript
moduleinstance.registerConnection('1');
```

Terrific Rocks!

**Comment by brunschgi** [comment]
This feature (in a little different way) is part of TerrificJS >= 1.1.0. Have a look at the documentation at http://terrifically.org/api/sandbox/#subscription
