### ISSUE TITLE
Using terrificjs with multiple versions of jQuery

### ISSUE THREAD

**Issue by tjunghans** [brunschgi/terrificjs#22]
**Scenario**
- jQuery-1.6.4 is used in a projectA
- A terrific module used in projectB with jQuery-1.8.1 is now going to be used in projectA as well.
- jQuery-1.8.1 and Terrific-2.0.1 are loaded with yepnope (or any other script loader).
- jQuery-1.8.1 is loaded with noConflict, so the $ is assigned to jQuery-1.6.4 and not -1.8.1. And **here lies the problem**. Terrific assigns $ to Tc.$. There is no way of specifying $, unless of course, the assignment is removed. 

**Wishes**
- It should be possible to tell Terrific which jQuery to use, no matter when Terrific is included.

**Comment by brunschgi** [comment]
Hi TJ

This is related to https://github.com/brunschgi/terrificjs/issues/9 :-)
Hope we will find a way to satisfy both needs…

This issues is also related to https://github.com/brunschgi/terrificjs/issues/23.

**Comment by brunschgi** [comment]
@tjunghans I solved the problem by looking for the base library to use in the following order:

```
/*
 * The base library object.
 */
Tc.$ = root.jQuery || root.Zepto || root.$;
```

So always the last loaded jQuery/Zepto version is used – at least as long as you do not use `noConflict(true)`.

**Comment by tjunghans** [comment]
@brunschgi Thanks! What is root in the example in your comment above?

**Comment by brunschgi** [comment]
@tjunghans 
Browsers: root = window | Server-side js: root = exports
But essentially the assignment needs to be performed on a object to not produce ReferenceErrors.
