### ISSUE TITLE
Some methods should not fail silently if params are incorrect

### ISSUE THREAD

**Issue by MarcDiethelm** [brunschgi/terrificjs#33]
For example
- `Tc.Sandbox.subscribe`
- `Tc.Sandbox.subscribe`

Should either throw an error or return boolean values if needed params are incorrect (especially `@param module`).

This makes debugging much easier.

**Comment by brunschgi** [comment]
Hi Marc

Thanks for your proposal. `Tc.Sandbox.subscribe` now throws an `Error` if there are any invalid parameters.

Hope this helps & Cheers
Remo

**Comment by MarcDiethelm** [comment]
Awesome, thank you!
