### ISSUE TITLE
Get rid of jQuery / Zepto dependency

### ISSUE THREAD

**Issue by brunschgi** [brunschgi/terrificjs#42]
TerrificJS does only use a very small subset of jQuery / Zepto. Therefore it would be nice if it would work without one of the two.

**Comment by christianhaller** [comment]
yay :+1:

**Comment by deniaz** [comment]
+1

**Comment by veith** [comment]
👍 super so

**Comment by brunschgi** [comment]
Glad to see that this is real need! 
This issue is done but is only a piece of the whole refactoring puzzle – so please be patient until 3.0.0 is released.
