### ISSUE TITLE
Method Call in Decorator results in Error

### ISSUE THREAD

**Issue by deniaz** [brunschgi/terrificjs#62]
I have created a new Module (lets call it `Foo`) and a Decorator (`Bar`), see [example files here](https://gist.github.com/deniaz/5728859126ba51079639).

Executing this results in an `TypeError: Cannot read property 'start' of undefined` error which is not traceable.

<img width="401" alt="screen shot 2015-10-01 at 18 24 50" src="https://cloud.githubusercontent.com/assets/698963/10226793/db2665e4-6869-11e5-9c2b-def897f6f270.png">

After calling `this.bar()`, the `_parent` property is not bound to `this` anymore and therefore `this._parent.start(resolve);` can't be called anymore. It doesn't matter what the `bar()` method does, an empty function body has the same effect as anything else.

I've played around with some things like `var mod = this; mod.bar();` and similar, but the problem still exists. Also adding an (empty) `bar()` method to `Foo` doesn't helper either.

It would be very helpful to use additional methods in a decorator ;) 

I'm using `3.0.0-beta.8`.

Cheers,
Rob

**Comment by brunschgi** [comment]
Hi Rob

Thanks for the bug report! After some debugging I found the problem with the `this._parent` handling for nested function calls. The commit above fixes the issue. 

Hope this helps.

Cheers,
Remo

**Comment by deniaz** [comment]
Brilliant, thank you.
