### ISSUE TITLE
Unregister module (remove module) should delete event listeners

### ISSUE THREAD

**Issue by buehler** [brunschgi/terrificjs#63]
When I remove some modules via _sandbox.removeModules, the event listeners are not removed. This results in an undefined exception when a event is called.

could be solved with:
removeAllListeners in unregisterModule (or before stop)

**Comment by brunschgi** [comment]
Hi Christoph

I tried to reproduce your error and probably found the issue. The event listeners are correctly removed in the stop method of the base module, but there is an issue when you call `_sandbox.removeModules` in an event listeners `on()` method. 

As this manipulates the array of registered eventEmitters during looping through the array the following error is thrown:

`Uncaught TypeError: Cannot read property 'handle' of undefined``

Hope the above commit solves your problem ;-)

Cheers
Remo

**Comment by buehler** [comment]
:+1: 
;-)
