### ISSUE TITLE
URGENT: http://terrifically.org is DOWN

### ISSUE THREAD

**Issue by tigerclaw-az** [brunschgi/terrificjs#70]
Receiving error when navigating to http://terrifically.org/api/module/

Network Error (tcp_error) 

A communication error occurred: "Operation timed out"
The Web Server may be down, too busy, or experiencing other problems preventing it from responding to requests. You may wish to try again at a later time.

For assistance, contact your network support team.

**Comment by brunschgi** [comment]
Hi Erik
Thanks for the info. We are currently moving the site to another location. It will be up again soon ;-)
Best, Remo

**Comment by tigerclaw-az** [comment]
Thanks Remo!
