### ISSUE TITLE
What is the use of Application?

### ISSUE THREAD

**Issue by jantimon** [brunschgi/terrificjs#71]
Hey - I am trying to get started with terrificjs.
Why is there a mix of the global `T.Modules` and a `new T.Application()` instance?
When should I use multiple application instances?

**Comment by brunschgi** [comment]
Hi Jan
I don't really get your question. There is no mix at all. All of the TerrificJS classes are namespaced under T and there are no global instances of these classes. Please refer to the documentation https://github.com/brunschgi/terrificjs for further information.
So to come to the main question: When should you use multiple application instances?
This is completely up to you. In most scenarios you are good to go with a single application instance. However if you have embedded applications – e.g. calculators, mini-apps etc – inside of a terrificjs page, it could make sense to have a separate application instance for them. 
Hope this helps
Best, Remo

**Comment by jantimon** [comment]
Alright thanks I'll go with one application 👍 
Just one more thing for clarification if I have one "mainApplication" which is started without context and a mini-app with context wouldn't that start the components of the mini-app twice?
