### ISSUE TITLE
Don't use jQuery.noConflict();

### ISSUE THREAD

**Issue by mhyz** [brunschgi/terrificjs#9]
Using of

``` javascript
    Tc.$ = jQuery.noConflict(false);
```

detaches window.$.

Since TerrificJs doesn't need window.$ but other jQuery plugins or so do, why not just:

``` javascript
    Tc.$ = jQuery;
```

?

**Comment by MarcDiethelm** [comment]
+1

In addition, I think its annoying to not have the $ global in the Firebug console.

**Comment by brunschgi** [comment]
The release of the global $ (noConflict mode) was made to not get in troubles with other javascript code that use jQuery or another framework using the $. You are right, this can be annoying or can cause conflicts with other jQuery plugins  although most often something like (function($) { … })(jQuery) helps.

I'm going to change this to the proposed Tc.$ = jQuery in v2.0 (have a look at the development branch for a first glimpse).

**Comment by mhyz** [comment]
Great, thanks!
